---
Name: mysiteroutes
After: 'framework/routes'
---
Director:
  rules:
    'bankapi': 'MobileApiController'
    'banking/account/$ID': 'AccountDetailController'
    'banking/product/$ID' : 'ProductDetailController'
    'banking/transfer/$ID' : 'TransferController'
    'banking': 'AccountController'
    'login': 'LoginController'
    '': 'AccountController'
    'image/$ImageId/$Width/$Height': 'ImageController'