---
Name: mysiteroutes
After: 'framework/routes'
---
Director:
  rules:
    'bankapi': 'MobileApiController'
    'banking/product/$ID' : 'ProductDetailController'
    'banking/account/$ID/$Month/$Year': 'AccountDetailController'
    'banking/account/$ID': 'AccountDetailController'
    'banking/transfer/$ID': 'TransferController'
    'budgeting/edit': 'BudgetEditController'
    'budgeting/categorise': 'CategoriseController'
    'rewards/claim': 'ClaimController'
    'rewards/spin': 'SpinController'
    'banking': 'AccountController'
    'budgeting': 'BudgetController'
    'rewards': 'RewardsController'
    'login': 'LoginController'
    '': 'AccountController'
    'image/$ImageId/$Width/$Height': 'ImageController'