---
Name: mysiteroutes
After: 'framework/routes'
---
Director:
  rules:
    '': 'AccountController'
    'banking': 'AccountController'
    'banking/account/$ID': 'AccountDetailController'
    'login': 'LoginController'
    'image/$ImageId/$Width/$Height': 'ImageController'